USE lubycon;

INSERT INTO `luby_contents_category` SET `contents_code` = 1, `contents_category` = 'artwork', `contents_category_detail` = 'Animation';
INSERT INTO `luby_contents_category` SET `contents_code` = 2, `contents_category` = 'artwork', `contents_category_detail` = 'Architecture';
INSERT INTO `luby_contents_category` SET `contents_code` = 3, `contents_category` = 'artwork', `contents_category_detail` = 'Avantgarde';
INSERT INTO `luby_contents_category` SET `contents_code` = 4, `contents_category` = 'artwork', `contents_category_detail` = 'Baroque';
INSERT INTO `luby_contents_category` SET `contents_code` = 5, `contents_category` = 'artwork', `contents_category_detail` = 'Design';
INSERT INTO `luby_contents_category` SET `contents_code` = 6, `contents_category` = 'artwork', `contents_category_detail` = 'Digital art';
INSERT INTO `luby_contents_category` SET `contents_code` = 7, `contents_category` = 'artwork', `contents_category_detail` = 'Drawing';
INSERT INTO `luby_contents_category` SET `contents_code` = 8, `contents_category` = 'artwork', `contents_category_detail` = 'Expressionism';
INSERT INTO `luby_contents_category` SET `contents_code` = 9, `contents_category` = 'artwork', `contents_category_detail` = 'Historical';
INSERT INTO `luby_contents_category` SET `contents_code` = 10, `contents_category` = 'artwork', `contents_category_detail` = 'Icons';
INSERT INTO `luby_contents_category` SET `contents_code` = 11, `contents_category` = 'artwork', `contents_category_detail` = 'Illustration';
INSERT INTO `luby_contents_category` SET `contents_code` = 12, `contents_category` = 'artwork', `contents_category_detail` = 'Impressionism';
INSERT INTO `luby_contents_category` SET `contents_code` = 13, `contents_category` = 'artwork', `contents_category_detail` = 'Landscape';
INSERT INTO `luby_contents_category` SET `contents_code` = 14, `contents_category` = 'artwork', `contents_category_detail` = 'Minimalism';
INSERT INTO `luby_contents_category` SET `contents_code` = 15, `contents_category` = 'artwork', `contents_category_detail` = 'Painting';
INSERT INTO `luby_contents_category` SET `contents_code` = 16, `contents_category` = 'artwork', `contents_category_detail` = 'Pop art';
INSERT INTO `luby_contents_category` SET `contents_code` = 17, `contents_category` = 'artwork', `contents_category_detail` = 'Portrait';
INSERT INTO `luby_contents_category` SET `contents_code` = 18, `contents_category` = 'artwork', `contents_category_detail` = 'Realism';
INSERT INTO `luby_contents_category` SET `contents_code` = 19, `contents_category` = 'artwork', `contents_category_detail` = 'Renaissance';
INSERT INTO `luby_contents_category` SET `contents_code` = 20, `contents_category` = 'artwork', `contents_category_detail` = 'Sculpture';
INSERT INTO `luby_contents_category` SET `contents_code` = 21, `contents_category` = 'artwork', `contents_category_detail` = 'Street art';
INSERT INTO `luby_contents_category` SET `contents_code` = 22, `contents_category` = 'artwork', `contents_category_detail` = 'Surrealism';
INSERT INTO `luby_contents_category` SET `contents_code` = 23, `contents_category` = 'artwork', `contents_category_detail` = 'UI/UX';
INSERT INTO `luby_contents_category` SET `contents_code` = 24, `contents_category` = 'artwork', `contents_category_detail` = 'Wallpaper';
INSERT INTO `luby_contents_category` SET `contents_code` = 25, `contents_category` = 'artwork', `contents_category_detail` = 'Web design';
INSERT INTO `luby_contents_category` SET `contents_code` = 26, `contents_category` = 'artwork', `contents_category_detail` = 'Various';


INSERT INTO `luby_contents_category` SET `contents_code` = 100, `contents_category` = 'vector', `contents_category_detail` = 'Animation';
INSERT INTO `luby_contents_category` SET `contents_code` = 101, `contents_category` = 'vector', `contents_category_detail` = 'Architecture';
INSERT INTO `luby_contents_category` SET `contents_code` = 102, `contents_category` = 'vector', `contents_category_detail` = 'Background';
INSERT INTO `luby_contents_category` SET `contents_code` = 103, `contents_category` = 'vector', `contents_category_detail` = 'Branding';
INSERT INTO `luby_contents_category` SET `contents_code` = 104, `contents_category` = 'vector', `contents_category_detail` = 'Decoration';
INSERT INTO `luby_contents_category` SET `contents_code` = 105, `contents_category` = 'vector', `contents_category_detail` = 'Fashion';
INSERT INTO `luby_contents_category` SET `contents_code` = 106, `contents_category` = 'vector', `contents_category_detail` = 'Furniture';
INSERT INTO `luby_contents_category` SET `contents_code` = 107, `contents_category` = 'vector', `contents_category_detail` = 'Graphic';
INSERT INTO `luby_contents_category` SET `contents_code` = 108, `contents_category` = 'vector', `contents_category_detail` = 'Icons';
INSERT INTO `luby_contents_category` SET `contents_code` = 109, `contents_category` = 'vector', `contents_category_detail` = 'Illustration';
INSERT INTO `luby_contents_category` SET `contents_code` = 110, `contents_category` = 'vector', `contents_category_detail` = 'Industries';
INSERT INTO `luby_contents_category` SET `contents_code` = 111, `contents_category` = 'vector', `contents_category_detail` = 'Landscape';
INSERT INTO `luby_contents_category` SET `contents_code` = 112, `contents_category` = 'vector', `contents_category_detail` = 'Logo';
INSERT INTO `luby_contents_category` SET `contents_code` = 113, `contents_category` = 'vector', `contents_category_detail` = 'Map';
INSERT INTO `luby_contents_category` SET `contents_code` = 114, `contents_category` = 'vector', `contents_category_detail` = 'Painting';
INSERT INTO `luby_contents_category` SET `contents_code` = 115, `contents_category` = 'vector', `contents_category_detail` = 'Printing';
INSERT INTO `luby_contents_category` SET `contents_code` = 116, `contents_category` = 'vector', `contents_category_detail` = 'Shape';
INSERT INTO `luby_contents_category` SET `contents_code` = 117, `contents_category` = 'vector', `contents_category_detail` = 'Symbols';
INSERT INTO `luby_contents_category` SET `contents_code` = 118, `contents_category` = 'vector', `contents_category_detail` = 'Technology';
INSERT INTO `luby_contents_category` SET `contents_code` = 119, `contents_category` = 'vector', `contents_category_detail` = 'Various';


INSERT INTO `luby_contents_category` SET `contents_code` = 200, `contents_category` = '3d', `contents_category_detail` = '3D Scans';
INSERT INTO `luby_contents_category` SET `contents_code` = 201, `contents_category` = '3d', `contents_category_detail` = 'Architecture';
INSERT INTO `luby_contents_category` SET `contents_code` = 202, `contents_category` = '3d', `contents_category_detail` = 'Art';
INSERT INTO `luby_contents_category` SET `contents_code` = 203, `contents_category` = '3d', `contents_category_detail` = 'Characters';
INSERT INTO `luby_contents_category` SET `contents_code` = 204, `contents_category` = '3d', `contents_category_detail` = 'DIY';
INSERT INTO `luby_contents_category` SET `contents_code` = 205, `contents_category` = '3d', `contents_category_detail` = 'Electronic';
INSERT INTO `luby_contents_category` SET `contents_code` = 206, `contents_category` = '3d', `contents_category_detail` = 'Fashion';
INSERT INTO `luby_contents_category` SET `contents_code` = 207, `contents_category` = '3d', `contents_category_detail` = 'Furniture';
INSERT INTO `luby_contents_category` SET `contents_code` = 208, `contents_category` = '3d', `contents_category_detail` = 'Game';
INSERT INTO `luby_contents_category` SET `contents_code` = 209, `contents_category` = '3d', `contents_category_detail` = 'Household';
INSERT INTO `luby_contents_category` SET `contents_code` = 210, `contents_category` = '3d', `contents_category_detail` = 'Industrial';
INSERT INTO `luby_contents_category` SET `contents_code` = 211, `contents_category` = '3d', `contents_category_detail` = 'Interior';
INSERT INTO `luby_contents_category` SET `contents_code` = 212, `contents_category` = '3d', `contents_category_detail` = 'Jwellery';
INSERT INTO `luby_contents_category` SET `contents_code` = 213, `contents_category` = '3d', `contents_category_detail` = 'Kitchen';
INSERT INTO `luby_contents_category` SET `contents_code` = 214, `contents_category` = '3d', `contents_category_detail` = 'Medical';
INSERT INTO `luby_contents_category` SET `contents_code` = 215, `contents_category` = '3d', `contents_category_detail` = 'Models';
INSERT INTO `luby_contents_category` SET `contents_code` = 216, `contents_category` = '3d', `contents_category_detail` = 'Object';
INSERT INTO `luby_contents_category` SET `contents_code` = 217, `contents_category` = '3d', `contents_category_detail` = 'Pets';
INSERT INTO `luby_contents_category` SET `contents_code` = 218, `contents_category` = '3d', `contents_category_detail` = 'Scenry';
INSERT INTO `luby_contents_category` SET `contents_code` = 219, `contents_category` = '3d', `contents_category_detail` = 'Sculpture';
INSERT INTO `luby_contents_category` SET `contents_code` = 220, `contents_category` = '3d', `contents_category_detail` = 'Tools';
INSERT INTO `luby_contents_category` SET `contents_code` = 221, `contents_category` = '3d', `contents_category_detail` = 'Toys';
INSERT INTO `luby_contents_category` SET `contents_code` = 222, `contents_category` = '3d', `contents_category_detail` = 'Vehicles';
INSERT INTO `luby_contents_category` SET `contents_code` = 223, `contents_category` = '3d', `contents_category_detail` = 'Various';